/*
 * JFrameValidar.java
 *
 * Created on 11 de mayo de 2007, 8:40
 */

package Interfaz;

import estdatos.*;
import java.util.Vector;

/**
 *
 * @author  Daniel Moral García
 */
public class JFrameValidar extends javax.swing.JFrame {
    Automata a = new Automata();
    
    /** Creates new form JFrameValidar */
    public JFrameValidar() {
        initComponents();
    }
    
    public JFrameValidar(Automata automata) {
        initComponents();
        a = new Automata(automata);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tbCadena = new javax.swing.JTextField();
        bValida = new javax.swing.JButton();
        lResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valida cadena");

        bValida.setText("Valida");
        bValida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bValidaMouseClicked(evt);
            }
        });

        lResultado.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        lResultado.setForeground(new java.awt.Color(0, 204, 0));
        lResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lResultado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(tbCadena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bValida))
                    .add(lResultado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tbCadena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bValida))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lResultado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bValidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bValidaMouseClicked
        if (tbCadena.getText()!="") {
            Estado etemp = new Estado();
            Vector aux = new Vector();
            Vector aux2 = new Vector();
            String simbActual,cadActual,nombreEstado;
            boolean reconocida=false;
            boolean sigue=true;

            aux2 = a.getSimbolos();
            nombreEstado = "";
            cadActual = tbCadena.getText();
            etemp = a.obtenerEstado(0);
            for (int i=0; (i<tbCadena.getText().length()) && sigue; i++) {
                simbActual = cadActual.substring(0,1);
                nombreEstado = nombreEstado + simbActual;
                cadActual = cadActual.substring(1);
                try {
                    aux = (Vector)a.getTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual));
                    etemp = (Estado)aux.elementAt(0);
                    if (etemp.getTipoEstado().equals("FINAL")) reconocida=true;
                    else reconocida=false;
                }
                catch (Exception err) {
                    sigue=false;
                    reconocida=false;
                }
            }
            if (reconocida) lResultado.setText("CADENA RECONOCIDA");
            else lResultado.setText("CADENA NO RECONOCIDA");

            tbCadena.setText("");
	    tbCadena.requestFocus();
        }
    }//GEN-LAST:event_bValidaMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameValidar().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bValida;
    private javax.swing.JLabel lResultado;
    private javax.swing.JTextField tbCadena;
    // End of variables declaration//GEN-END:variables
    
}
