/*
 * JFrameMostrarAP.java
 *
 * Created on 21 de marzo de 2007, 15:17
 */

package Interfaz;

import estdatos.*;
import java.util.Vector;

/**
 *
 * @author  Daniel Moral García
 */
public class JFrameMostrarAP extends javax.swing.JFrame {
    
    /** Creates new form JFrameMostrarAP */
    public JFrameMostrarAP() {
        initComponents();
    }
    
    /** Creates new form JFrameMostrarAP */
    public JFrameMostrarAP(Automata ap) {
        initComponents();
        Estado aux = new Estado();
        Vector auxI = new Vector();
        Vector auxF = new Vector();
        
        //Rellenamos las casillas de resultado.
        Vector s = new Vector(ap.getSimbolos());
        for (int i=0; i<s.size(); i++)
            //Alfabeto de entrada (resultado)
            cbAlfEntrAP.addItem(s.elementAt(i).toString());
        for (int i=0; i<ap.obtenerNumeroEstados(); i++) {
            aux = ap.obtenerEstado(i);
            if (aux.getTipoEstado().equals("INICIAL/FINAL")) {
                auxI.addElement(aux.getEstado(0));
                auxF.addElement(aux.getEstado(0));
            }
            else if (aux.getTipoEstado().equals("INICIAL"))
                auxI.addElement(aux.getEstado(0));
            else if (aux.getTipoEstado().equals("FINAL"))
                auxF.addElement(aux.getEstado(0));
        }
        jList2.setListData(auxI);
        jList1.setListData(auxF);
        
        // Ahora mostramos las transiciones
        String cad;
        ModeloTabla miModelo = new ModeloTabla(ap.obtenerNumeroEstados(),s.size()+1);
        miModelo.setNombreColumna(0,"Estados");
        for (int i=0; i<s.size(); i++)
             miModelo.setNombreColumna(i+1,s.elementAt(i).toString());
        Vector vtmp = new Vector();
        Estado tmp = new Estado();
                cad = "";
        int k;
        for (int i=0; i<ap.obtenerNumeroEstados(); i++) {
            tmp = ap.obtenerEstado(i);
            cad = (String)tmp.getNombreEstado().elementAt(0);
            for (int j=1; j<tmp.obtenerNumeroEstados(); j++) {
                cad = cad+",";
                cad = cad+(String)tmp.getNombreEstado().elementAt(j);
            }
            miModelo.setValueAt(cad,i,0);
            for (int j=0; j<s.size(); j++) {
                try {
                    vtmp = (Vector)ap.getTransicion(i,j);
                    for (int z=0; z<vtmp.size(); z++) {
                        cad = "";
                        tmp = (Estado)vtmp.elementAt(z);
                        cad = tmp.getEstado(0);
                        for (k=1; k<tmp.getNumEstados(); k++)
                            cad = cad+","+tmp.getEstado(k);
                    }
                    miModelo.setValueAt(cad,i,j+1);
                }
                catch (Exception error) {
                    miModelo.setValueAt("-",i,j+1);
                }
            }
        }
        tAPFunDelta.setModel(miModelo);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lAPEstIniciales = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAlfEntrAP = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAPFunDelta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arbol de prefijos");
        setResizable(false);
        lAPEstIniciales.setText("Iniciales:");

        jLabel2.setText("Alfabeto de entrada:");

        jLabel4.setText("Funci\u00f3n delta:");

        tAPFunDelta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tAPFunDelta);

        jLabel1.setText("Finales:");

        jScrollPane1.setViewportView(jList1);

        jScrollPane3.setViewportView(jList2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(lAPEstIniciales)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbAlfEntrAP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lAPEstIniciales)
                        .add(cbAlfEntrAP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel2)
                        .add(jLabel1))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane3, 0, 0, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMostrarAP().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAlfEntrAP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lAPEstIniciales;
    private javax.swing.JTable tAPFunDelta;
    // End of variables declaration//GEN-END:variables
    
}
