/*
 * JFramePrincipal.java
 *
 * Created on 9 de enero de 2007, 17:14
 */

package Interfaz;

import estdatos.*;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Vector;
import javax.swing.*;
import javax.swing.JOptionPane;
import pelr.AlgoritmoIM1;
import pelr.AlgoritmoKC;
import java.io.*;


/**
 *
 * @author  Daniel Moral García
 */
public class JFramePrincipal extends javax.swing.JFrame {
    
    //Declaracion de variables
    Vector mpos = new Vector();
    Vector mneg = new Vector();
    Vector minc = new Vector();
    Automata a = new Automata();
    Automata ap = new Automata();
    double miclet = Double.MAX_VALUE;
    boolean apGenerado = false;
    boolean sCalculado = false;
    
    /** Creates new form JFramePrincipal */
    public JFramePrincipal() {
        initComponents();
        bAddMPos.setVisible(true);
        bDelMPos.setVisible(true);
        bGeneraS.setVisible(false);
        tbMPos.setVisible(true);
        cbMPos.setVisible(true);
        jLabel3.setVisible(true);
        cbValoresK.setVisible(true);
        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
        cbValoresS.setVisible(false);
        tbMNeg.setVisible(false);
        bAddMNeg.setVisible(false);
        bDelMNeg.setVisible(false);
        cbMNeg.setVisible(false);
        bAddCadenaKC.setVisible(false);
        tbAddCadenaKC.setVisible(false);
        bBorrarMPos.setVisible(true);
        bBorrarMNeg.setVisible(false);
        jLabelKCNeg.setVisible(false);
        jLabelValKenKC.setVisible(false);
        bVerAP.setEnabled(false);
        cbMInc.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        bEjecutar = new javax.swing.JButton();
        lSelAlg = new javax.swing.JLabel();
        cbSelAlg = new javax.swing.JComboBox();
        pParametros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbMPos = new javax.swing.JTextField();
        bAddMPos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tbMNeg = new javax.swing.JTextField();
        bAddMNeg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbValoresS = new javax.swing.JComboBox();
        bDelMPos = new javax.swing.JButton();
        bDelMNeg = new javax.swing.JButton();
        cbMPos = new javax.swing.JComboBox();
        cbMNeg = new javax.swing.JComboBox();
        bGeneraS = new javax.swing.JButton();
        cbValoresK = new javax.swing.JComboBox();
        bBorrarMPos = new javax.swing.JButton();
        bBorrarMNeg = new javax.swing.JButton();
        pResultados = new javax.swing.JPanel();
        lAlfEntrRes = new javax.swing.JLabel();
        lEstIniciales = new javax.swing.JLabel();
        lDeltaRes = new javax.swing.JLabel();
        jScrollPaneFD = new javax.swing.JScrollPane();
        tFunDelta = new javax.swing.JTable();
        cbAlfEntrRes = new javax.swing.JComboBox();
        bVerAP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbAddCadenaKC = new javax.swing.JTextField();
        bAddCadenaKC = new javax.swing.JButton();
        lEstFinales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlEstIniciales = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlEstFinales = new javax.swing.JList();
        jLabelKCNeg = new javax.swing.JLabel();
        jLabelValKenKC = new javax.swing.JLabel();
        cbMInc = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuMuestraPos = new javax.swing.JMenu();
        jMenuItemCargarPos = new javax.swing.JMenuItem();
        jMenuItemGuardarPos = new javax.swing.JMenuItem();
        jMenuMuestraNeg = new javax.swing.JMenu();
        jMenuItemCargarNeg = new javax.swing.JMenuItem();
        jMenuItemGuardarNeg = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAutomata = new javax.swing.JMenu();
        jMenuItemExportar = new javax.swing.JMenuItem();
        jMenuValidar = new javax.swing.JMenu();
        jMenuItemValidar = new javax.swing.JMenuItem();
        jMenuItemValidarConjunto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuGuardar = new javax.swing.JMenu();
        jMenuItemNormal = new javax.swing.JMenuItem();
        jMenuItemCompacto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuApGuardar = new javax.swing.JMenu();
        jMenuItemApNormal = new javax.swing.JMenuItem();
        jMenuItemApCompacto = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmos de Inducci\u00f3n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frPrincipal");
        setResizable(false);
        bEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/run_exec.png")));
        bEjecutar.setText("Ejecutar");
        bEjecutar.setToolTipText("Ejecuta la aplicaci\u00f3n con el algoritmo seleccionado y los par\u00e1metros deseados");
        bEjecutar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bEjecutarItemStateChanged(evt);
            }
        });
        bEjecutar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bEjecutarPropertyChange(evt);
            }
        });
        bEjecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEjecutarMouseClicked(evt);
            }
        });

        lSelAlg.setText("Selecciona un algoritmo:");
        lSelAlg.setToolTipText("Selecci\u00f3n de algoritmo y heur\u00edstico con que se va a ejecutar la apliaci\u00f3n");

        cbSelAlg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IM1 con k-sufijos", "IM1 con Levine", "IM1 con Miclet", "KC", "KC incremental", "KC con muestra negativa" }));
        cbSelAlg.setToolTipText("Selecci\u00f3n de algoritmo y heur\u00edstico con que se va a ejecutar la apliaci\u00f3n");
        cbSelAlg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelAlgItemStateChanged(evt);
            }
        });

        pParametros.setBorder(javax.swing.BorderFactory.createTitledBorder("Par\u00e1metros"));
        jLabel1.setText("Muestra Positiva:");

        bAddMPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/bAddCadena.png")));
        bAddMPos.setToolTipText("A\u00f1ade el elemento a la muestra positiva del lenguaje");
        bAddMPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMPosActionPerformed(evt);
            }
        });
        bAddMPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddMPosMouseClicked(evt);
            }
        });

        jLabel2.setText("Muestra Negativa:");

        bAddMNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/bAddCadena.png")));
        bAddMNeg.setToolTipText("A\u00f1ade un elemento a la muestra negativa del lenguaje");
        bAddMNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddMNegMouseClicked(evt);
            }
        });

        jLabel3.setText("Valor K:");
        jLabel3.setToolTipText("Selecciona un valor para el heur\u00edstico de los K-Sufijos");

        jLabel4.setText("Valor S:");
        jLabel4.setToolTipText("Selecciona un valor para el heur\u00edstico de Levine");

        cbValoresS.setToolTipText("Selecciona un valor para el heur\u00edstico de Levine");
        cbValoresS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbValoresSItemStateChanged(evt);
            }
        });

        bDelMPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/bDelCadena.png")));
        bDelMPos.setToolTipText("Elimina el elemento seleccionado de la muestra positiva");
        bDelMPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDelMPosMouseClicked(evt);
            }
        });

        bDelMNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/bDelCadena.png")));
        bDelMNeg.setToolTipText("Elimina el elemento seleccionado de la muestra negativa");
        bDelMNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDelMNegMouseClicked(evt);
            }
        });

        cbMPos.setMaximumSize(new java.awt.Dimension(24, 19));

        cbMNeg.setMaximumSize(new java.awt.Dimension(24, 19));

        bGeneraS.setText("Calcular");
        bGeneraS.setToolTipText("Genera la tabla de valores de S, usada en los heur\u00edsticos de Levine y Miclet");
        bGeneraS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGeneraSMouseClicked(evt);
            }
        });

        cbValoresK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbValoresKItemStateChanged(evt);
            }
        });

        bBorrarMPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icon_delete.png")));
        bBorrarMPos.setToolTipText("Elimina todas las cadenas de la muestra positiva");
        bBorrarMPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBorrarMPosMouseClicked(evt);
            }
        });

        bBorrarMNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/icon_delete.png")));
        bBorrarMNeg.setToolTipText("Elimina todas las cadenas de la muestra negativa");
        bBorrarMNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBorrarMNegMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pParametrosLayout = new org.jdesktop.layout.GroupLayout(pParametros);
        pParametros.setLayout(pParametrosLayout);
        pParametrosLayout.setHorizontalGroup(
            pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tbMNeg)
                    .add(tbMPos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(bAddMPos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(bAddMNeg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bDelMPos)
                    .add(bDelMNeg))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cbMPos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbMNeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(bBorrarMPos)
                    .add(bBorrarMNeg))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(cbValoresK, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(cbValoresS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bGeneraS)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        pParametrosLayout.setVerticalGroup(
            pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pParametrosLayout.createSequentialGroup()
                .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pParametrosLayout.createSequentialGroup()
                        .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(bAddMPos)
                            .add(tbMPos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bDelMPos)
                            .add(cbMPos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bBorrarMPos))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(bAddMNeg)
                            .add(tbMNeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bDelMNeg)
                            .add(bBorrarMNeg)
                            .add(cbMNeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(pParametrosLayout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(bGeneraS))
                    .add(pParametrosLayout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(cbValoresS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(pParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel3)
                        .add(cbValoresK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Aut\u00f3mata Inducido"));
        lAlfEntrRes.setText("Alfabeto de entrada:");

        lEstIniciales.setText("Estados Iniciales:");

        lDeltaRes.setText("Funci\u00f3n delta:");

        jScrollPaneFD.setEnabled(false);
        jScrollPaneFD.setFocusable(false);
        tFunDelta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tFunDelta.setFocusable(false);
        jScrollPaneFD.setViewportView(tFunDelta);

        bVerAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/ap.png")));
        bVerAP.setText("Ver AP");
        bVerAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVerAPMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Tiempo de ejecuci\u00f3n:");

        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("0 milisegundos");

        bAddCadenaKC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/addCadena.png")));
        bAddCadenaKC.setText("A\u00f1adir Cadena");
        bAddCadenaKC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddCadenaKCMouseClicked(evt);
            }
        });

        lEstFinales.setText("Estados Finales:");

        jScrollPane1.setViewportView(jlEstIniciales);

        jScrollPane2.setViewportView(jlEstFinales);

        jLabelKCNeg.setForeground(new java.awt.Color(0, 153, 51));
        jLabelKCNeg.setText("Valor de K:");

        jLabelValKenKC.setForeground(new java.awt.Color(0, 153, 51));
        jLabelValKenKC.setText("0");

        org.jdesktop.layout.GroupLayout pResultadosLayout = new org.jdesktop.layout.GroupLayout(pResultados);
        pResultados.setLayout(pResultadosLayout);
        pResultadosLayout.setHorizontalGroup(
            pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPaneFD, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pResultadosLayout.createSequentialGroup()
                        .add(lEstIniciales)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(lEstFinales)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lAlfEntrRes)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbAlfEntrRes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lDeltaRes)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pResultadosLayout.createSequentialGroup()
                        .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pResultadosLayout.createSequentialGroup()
                                .add(tbAddCadenaKC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(bAddCadenaKC))
                            .add(bVerAP))
                        .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pResultadosLayout.createSequentialGroup()
                                .add(17, 17, 17)
                                .add(jLabelKCNeg)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelValKenKC)
                                .add(285, 285, 285)
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6))
                            .add(pResultadosLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cbMInc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pResultadosLayout.setVerticalGroup(
            pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lEstIniciales)
                        .add(cbAlfEntrRes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(lAlfEntrRes)
                        .add(lEstFinales))
                    .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, 0, 0, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                .add(22, 22, 22)
                .add(lDeltaRes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneFD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(9, 9, 9)
                .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tbAddCadenaKC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bAddCadenaKC)
                    .add(cbMInc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel6)
                        .add(jLabel5))
                    .add(pResultadosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(bVerAP)
                        .add(jLabelKCNeg)
                        .add(jLabelValKenKC)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuArchivo.setText("Archivo");
        jMenuMuestraPos.setText("Muestra Positiva");
        jMenuItemCargarPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/abrir.png")));
        jMenuItemCargarPos.setText("Cargar");
        jMenuItemCargarPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarPosActionPerformed(evt);
            }
        });

        jMenuMuestraPos.add(jMenuItemCargarPos);

        jMenuItemGuardarPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/guardar.png")));
        jMenuItemGuardarPos.setText("Guardar");
        jMenuItemGuardarPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarPosActionPerformed(evt);
            }
        });

        jMenuMuestraPos.add(jMenuItemGuardarPos);

        jMenuArchivo.add(jMenuMuestraPos);

        jMenuMuestraNeg.setText("Muestra Negativa");
        jMenuItemCargarNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/abrir.png")));
        jMenuItemCargarNeg.setText("Cargar");
        jMenuItemCargarNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarNegActionPerformed(evt);
            }
        });

        jMenuMuestraNeg.add(jMenuItemCargarNeg);

        jMenuItemGuardarNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/guardar.png")));
        jMenuItemGuardarNeg.setText("Guardar");
        jMenuItemGuardarNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarNegActionPerformed(evt);
            }
        });

        jMenuMuestraNeg.add(jMenuItemGuardarNeg);

        jMenuArchivo.add(jMenuMuestraNeg);

        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/salir.png")));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });

        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuAutomata.setText("Automata");
        jMenuItemExportar.setText("Exportar");
        jMenuItemExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExportarActionPerformed(evt);
            }
        });

        jMenuAutomata.add(jMenuItemExportar);

        jMenuValidar.setText("Validar");
        jMenuItemValidar.setText("Cadena");
        jMenuItemValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidarActionPerformed(evt);
            }
        });

        jMenuValidar.add(jMenuItemValidar);

        jMenuItemValidarConjunto.setText("Conjunto de cadenas");
        jMenuItemValidarConjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidarConjuntoActionPerformed(evt);
            }
        });

        jMenuValidar.add(jMenuItemValidarConjunto);

        jMenuAutomata.add(jMenuValidar);

        jMenuAutomata.add(jSeparator1);

        jMenuGuardar.setText("Guardar Resultados");
        jMenuItemNormal.setText("Completo");
        jMenuItemNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNormalActionPerformed(evt);
            }
        });

        jMenuGuardar.add(jMenuItemNormal);

        jMenuItemCompacto.setText("Compacto");
        jMenuItemCompacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompactoActionPerformed(evt);
            }
        });

        jMenuGuardar.add(jMenuItemCompacto);

        jMenuAutomata.add(jMenuGuardar);

        jMenuAutomata.add(jSeparator2);

        jMenuApGuardar.setText("Arbol de Prefijos");
        jMenuItemApNormal.setText("Completo");
        jMenuItemApNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApNormalActionPerformed(evt);
            }
        });

        jMenuApGuardar.add(jMenuItemApNormal);

        jMenuItemApCompacto.setText("Compacto");
        jMenuItemApCompacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApCompactoActionPerformed(evt);
            }
        });

        jMenuApGuardar.add(jMenuItemApCompacto);

        jMenuAutomata.add(jMenuApGuardar);

        jMenuBar1.add(jMenuAutomata);

        jMenuAyuda.setText("Ayuda");
        jMenuItemAyuda.setText("Contenidos");
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });

        jMenuAyuda.add(jMenuItemAyuda);

        jMenuItemAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/help.png")));
        jMenuItemAcercaDe.setText("Acerca de ...");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });

        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pResultados, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(pParametros, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(lSelAlg)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cbSelAlg, 0, 670, Short.MAX_VALUE))))
                    .add(layout.createSequentialGroup()
                        .add(339, 339, 339)
                        .add(bEjecutar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lSelAlg)
                    .add(cbSelAlg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pParametros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bEjecutar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pResultados, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemValidarConjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidarConjuntoActionPerformed
        Vector mValidar = new Vector();
        int buenas = 0;
        int malas = 0;
        boolean reconocida=false;
        boolean sigue=true;
        //Abrimos el fichero con las cadenas.
        try {
            JPanel panel = new JPanel(); 
            Cargar_fichero c = new Cargar_fichero(panel);
            
            String tF = c.filename;
            FileReader fr = new FileReader(tF);
            BufferedReader bw = new BufferedReader(fr);

            String t = bw.readLine();
            for (int i=0; t!=null; i++) {
                mValidar.addElement(t);
                t = bw.readLine();
            }
            //Si abre, comprobamos las cadenas.
            for (int n=0; n<mValidar.size(); n++) {
                Estado etemp = new Estado();
                Vector aux = new Vector();
                Vector aux2 = new Vector();
                String simbActual,cadActual,nombreEstado;

                aux2 = a.getSimbolos();
                nombreEstado = "";
                cadActual = mValidar.elementAt(n).toString();
                etemp = a.obtenerEstado(0);
                sigue=true;
                for (int i=0; (i<((String)mValidar.elementAt(n)).length()) && sigue; i++) {
                    simbActual = cadActual.substring(0,1);
                    nombreEstado = nombreEstado + simbActual;
                    cadActual = cadActual.substring(1);
                    try {
                        aux = (Vector)a.getTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual));
                        etemp = (Estado)aux.elementAt(0);
                        if (etemp.getTipoEstado().equals("FINAL")) reconocida=true;
                        else reconocida=false;
                    }
                    catch (Exception err) {
                        sigue=false;
                        reconocida=false;
                    }
                }
                if (reconocida) buenas++;
                else malas++;
            }
            float media = (float)malas / ((float)buenas+(float)malas);
            System.out.println(malas+" "+buenas+" "+media);
            JOptionPane.showMessageDialog(null,"Cadenas reconocidas: "+buenas+"\nCadenas no reconocidas: "+malas+"\n" +
                    "Porcentaje de errores: "+media*100+" %","Validar conjunto",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception err) {
            //Si no abre, se da error y se sale de la función.
	    JOptionPane.showMessageDialog(null,"Error al cargar muestra de test","Validar conjunto",JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jMenuItemValidarConjuntoActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        Runtime rt = Runtime.getRuntime();
        File prueba = new File("Ayuda/manualDocu.chm");
        try {
            rt.exec("hh.exe "+prueba.getAbsolutePath());
        }
        catch(Exception err) {
            System.out.println(prueba.getAbsolutePath());
            JOptionPane.showMessageDialog(null,"No se ha podido cargar la aplicacion\nAsegurate de que este bien instalada","Error de ejecución",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void bAddMPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMPosActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_bAddMPosActionPerformed

    private void jMenuItemValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidarActionPerformed
        if (!bEjecutar.isEnabled()||cbSelAlg.getSelectedIndex()==4) {
	    JFrameValidar pValida = new JFrameValidar(a);
	    pValida.setEnabled(true);
	    pValida.setVisible(true);
	}
	else {
	    JOptionPane.showMessageDialog(null,"No hay autómata inducido","Validacion de cadenas",JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jMenuItemValidarActionPerformed

    private void bEjecutarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bEjecutarPropertyChange

    }//GEN-LAST:event_bEjecutarPropertyChange

    private void bEjecutarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bEjecutarItemStateChanged

    }//GEN-LAST:event_bEjecutarItemStateChanged

    private void cbValoresSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbValoresSItemStateChanged
        bEjecutar.setEnabled(true);
    }//GEN-LAST:event_cbValoresSItemStateChanged

    private void cbValoresKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbValoresKItemStateChanged
        bEjecutar.setEnabled(true);
    }//GEN-LAST:event_cbValoresKItemStateChanged

    private void bBorrarMNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBorrarMNegMouseClicked
        if (JOptionPane.showConfirmDialog(null,"Confirmar para borrar muestra","Eliminar muestra",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
            mneg.removeAllElements();
            cbMNeg.removeAllItems();
            bEjecutar.setEnabled(true);
        }
    }//GEN-LAST:event_bBorrarMNegMouseClicked

    /**
     *@param evt Un evento
     *@return No devuelve nada
     */
    private void bBorrarMPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBorrarMPosMouseClicked
        if (JOptionPane.showConfirmDialog(null,"Confirmar para borrar muestra","Eliminar muestra",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
            mpos.removeAllElements();
            cbMPos.removeAllItems();
            bEjecutar.setEnabled(true);
            bVerAP.setEnabled(false);
        }
    }//GEN-LAST:event_bBorrarMPosMouseClicked

    /**
     *@param evt
     *@return No devuelve nada
     */
    /**
     *  Funcion que añade una cadena a la muestra para el algoritmo KC incremental
    *@Param evt
    *@Return No devuelve nada
    */
    private void bAddCadenaKCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddCadenaKCMouseClicked
        if (tbAddCadenaKC.getText()!="") {
            Estado etemp = new Estado();
            Vector aux = new Vector();
            Vector aux2 = new Vector();
            String simbActual,cadActual,nombreEstado;
            boolean reconocida=false;

            aux2 = a.getSimbolos();
            nombreEstado = "";
            cadActual = tbAddCadenaKC.getText();
            etemp = a.obtenerEstado(0);
            if (cadActual.equals("%")) {
                int indice = a.buscarEstado(etemp);
                a.obtenerEstado(indice).putTipoEstado("INICIAL/FINAL");
            }
            else {
                for (int i=0; i<tbAddCadenaKC.getText().length(); i++) {
                    simbActual = cadActual.substring(0,1);
                    nombreEstado = nombreEstado + simbActual;
                    cadActual = cadActual.substring(1);
                    try {
                        aux = (Vector)a.getTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual));
                        etemp = (Estado)aux.elementAt(0);
                        if (etemp.getTipoEstado().equals("FINAL")) reconocida=true;
                        else reconocida=false;
                    }
                    catch (Exception err) {
                        if (nombreEstado.equals(tbAddCadenaKC.getText())) {
                            Estado et = new Estado(nombreEstado,"FINAL");
                            a.addEstado(et);
                            if (!aux2.contains(simbActual)) {
                                aux2.addElement(simbActual);
                                a.addSimbolo(simbActual);
                            }
                            a.addTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual),et);
                            try {
                                aux = (Vector)a.getTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual));
                            }
                            catch(Exception err2) {}
                            etemp = (Estado)aux.elementAt(0);
                        }
                        else {
                            Estado et = new Estado(nombreEstado,"INTERMEDIO");
                            a.addEstado(et);
                            if (!aux2.contains(simbActual)) {
                                aux2.addElement(simbActual);
                                a.addSimbolo(simbActual);
                            }
                            a.addTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual),et);
                            try {
                                aux = (Vector)a.getTransicion(a.buscarEstado(etemp),aux2.indexOf(simbActual));
                            }
                            catch(Exception err2){}
                            etemp = (Estado)aux.elementAt(0);
                        }
                        reconocida=false;
                    }
                }
                if (!etemp.getTipoEstado().equals("FINAL")) {
                    int indice = a.buscarEstado(etemp);
                    a.obtenerEstado(indice).putTipoEstado("FINAL");
                }
            }
            if (reconocida) JOptionPane.showMessageDialog(null,"La cadena ya es reconocida por el automata","KC Incremental",JOptionPane.INFORMATION_MESSAGE);
            else { 
                JOptionPane.showMessageDialog(null,"Nueva cadena añadida","KC Incremental",JOptionPane.INFORMATION_MESSAGE);
                if (!minc.contains(tbAddCadenaKC.getText())) minc.addElement(tbAddCadenaKC.getText());
            }

            a = AlgoritmoKC.ejecutar(a,cbSelAlg.getSelectedIndex(),Integer.decode(cbValoresK.getSelectedItem().toString()).intValue(),mneg);
            tbAddCadenaKC.setText("");
	    tbAddCadenaKC.requestFocus();
            actualizaMInc();
            mostrarResultados();
        }
    }//GEN-LAST:event_bAddCadenaKCMouseClicked

    private void actualizaMInc() {
        cbMInc.removeAllItems();
        for (int i=0; i<minc.size(); i++)
            cbMInc.addItem(minc.elementAt(i));
    }
    
    /**
     *@param evt
     *@return No devuelve nada
     */
    private void cbSelAlgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelAlgItemStateChanged
        switch(cbSelAlg.getSelectedIndex()) {
            case 0: //IM1 con k-Sufijos
                bAddMPos.setVisible(true);
                bDelMPos.setVisible(true);
                bGeneraS.setVisible(false);
                tbMPos.setVisible(true);
                cbMPos.setVisible(true);
                jLabel3.setVisible(true);
                cbValoresK.setVisible(true);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                cbValoresS.setVisible(false);
                tbMNeg.setVisible(false);
                bAddMNeg.setVisible(false);
                bDelMNeg.setVisible(false);
                cbMNeg.setVisible(false);
                bAddCadenaKC.setVisible(false);
                tbAddCadenaKC.setVisible(false);
                bBorrarMPos.setVisible(true);
                bBorrarMNeg.setVisible(false);
                jLabelKCNeg.setVisible(false);
                jLabelValKenKC.setVisible(false);
                bEjecutar.setEnabled(true);
                cbMInc.setVisible(false);
                break;
            case 1: //IM1 con Levine
                bAddMPos.setVisible(true);
                bDelMPos.setVisible(true);
                bGeneraS.setVisible(true);
                tbMPos.setVisible(true);
                cbMPos.setVisible(true);
                jLabel3.setVisible(false);
                cbValoresK.setVisible(false);
                jLabel2.setVisible(false);
                jLabel4.setVisible(true);
                cbValoresS.setVisible(true);
                tbMNeg.setVisible(false);
                bAddMNeg.setVisible(false);
                bDelMNeg.setVisible(false);
                cbMNeg.setVisible(false);
                bAddCadenaKC.setVisible(false);
                tbAddCadenaKC.setVisible(false);
                bBorrarMPos.setVisible(true);
                bBorrarMNeg.setVisible(false);
                jLabelKCNeg.setVisible(false);
                jLabelValKenKC.setVisible(false);
                bEjecutar.setEnabled(true);
                cbMInc.setVisible(false);
                break;
            case 2: //IM1 con Miclet
                bAddMPos.setVisible(true);
                bDelMPos.setVisible(true);
                bGeneraS.setVisible(false);
                tbMPos.setVisible(true);
                cbMPos.setVisible(true);
                jLabel3.setVisible(false);
                cbValoresK.setVisible(false);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                cbValoresS.setVisible(false);
                tbMNeg.setVisible(false);
                bAddMNeg.setVisible(false);
                bDelMNeg.setVisible(false);
                cbMNeg.setVisible(false);
                bAddCadenaKC.setVisible(false);
                tbAddCadenaKC.setVisible(false);
                bBorrarMPos.setVisible(true);
                bBorrarMNeg.setVisible(false);
                jLabelKCNeg.setVisible(false);
                jLabelValKenKC.setVisible(false);
                bEjecutar.setEnabled(true);
                cbMInc.setVisible(false);
                break;
            case 3: //KC
                bAddMPos.setVisible(true);
                bDelMPos.setVisible(true);
                bGeneraS.setVisible(false);
                tbMPos.setVisible(true);
                cbMPos.setVisible(true);
                jLabel3.setVisible(true);
                cbValoresK.setVisible(true);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                cbValoresS.setVisible(false);
                tbMNeg.setVisible(false);
                bAddMNeg.setVisible(false);
                bDelMNeg.setVisible(false);
                cbMNeg.setVisible(false);
                bAddCadenaKC.setVisible(false);
                tbAddCadenaKC.setVisible(false);
                bBorrarMPos.setVisible(true);
                bBorrarMNeg.setVisible(false);
                jLabelKCNeg.setVisible(false);
                jLabelValKenKC.setVisible(false);
                bEjecutar.setEnabled(true);
                cbMInc.setVisible(false);
                break;
            case 4: //KC incremental
                bAddMPos.setVisible(true);
                bDelMPos.setVisible(true);
                bGeneraS.setVisible(false);
                tbMPos.setVisible(true);
                cbMPos.setVisible(true);
                jLabel3.setVisible(true);
                cbValoresK.setVisible(true);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                cbValoresS.setVisible(false);
                tbMNeg.setVisible(false);
                bAddMNeg.setVisible(false);
                bDelMNeg.setVisible(false);
                cbMNeg.setVisible(false);
                bAddCadenaKC.setVisible(true);
                tbAddCadenaKC.setVisible(true);
                bBorrarMPos.setVisible(true);
                bBorrarMNeg.setVisible(false);
                jLabelKCNeg.setVisible(false);
                jLabelValKenKC.setVisible(false);
                bEjecutar.setEnabled(true);
                cbMInc.setVisible(true);
                break;
            case 5: //KC con muestra negativa
                bAddMPos.setVisible(true);
                bDelMPos.setVisible(true);
                bGeneraS.setVisible(false);
                tbMPos.setVisible(true);
                cbMPos.setVisible(true);
                jLabel3.setVisible(false);
                cbValoresK.setVisible(false);
                jLabel2.setVisible(true);
                jLabel4.setVisible(false);
                cbValoresS.setVisible(false);
                tbMNeg.setVisible(true);
                bAddMNeg.setVisible(true);
                bDelMNeg.setVisible(true);
                cbMNeg.setVisible(true);
                bAddCadenaKC.setVisible(false);
                tbAddCadenaKC.setVisible(false);
                bBorrarMPos.setVisible(true);
                bBorrarMNeg.setVisible(true);
                jLabelKCNeg.setVisible(true);
                jLabelValKenKC.setVisible(true);
                bEjecutar.setEnabled(true);
                cbMInc.setVisible(false);
                break;
        }
    }//GEN-LAST:event_cbSelAlgItemStateChanged

    /**
     *@param evt
     *@return No devuelve nada
     */
    private void jMenuItemApCompactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApCompactoActionPerformed
        JPanel panel = new JPanel(); 
        Guardar_como g = new Guardar_como(panel);
        if (g.filename!="") {
            ap.guardarAutomata(true,g.filename);
            JOptionPane.showMessageDialog(null,"Automata guardado (Compacto)","Arbol de prefijos",JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_jMenuItemApCompactoActionPerformed

    private void jMenuItemApNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApNormalActionPerformed
        JPanel panel = new JPanel(); 
        Guardar_como g = new Guardar_como(panel);
        if (g.filename!="") {
            ap.guardarAutomata(false,g.filename);
            JOptionPane.showMessageDialog(null,"Automata guardado (Completo)","Arbol de prefijos",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemApNormalActionPerformed

    private void jMenuItemCompactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompactoActionPerformed
        JPanel panel = new JPanel(); 
        Guardar_como g = new Guardar_como(panel);
        if (g.filename!="") {
            a.guardarAutomata(true,g.filename);
            JOptionPane.showMessageDialog(null,"Automata guardado (Compacto)","Automata Resultado",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemCompactoActionPerformed

    private void jMenuItemNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNormalActionPerformed
        JPanel panel = new JPanel(); 
        Guardar_como g = new Guardar_como(panel);
        if (g.filename!="") {
            a.guardarAutomata(false,g.filename);
            JOptionPane.showMessageDialog(null,"Automata guardado (Completo)","Automata Resultado",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemNormalActionPerformed

    private void jMenuItemExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExportarActionPerformed
        AutomataOutput salida = new AutomataOutput();
        
        try {
            salida.abrir();
            salida.escribir(a);
            salida.cerrar();
            JOptionPane.showMessageDialog(null,"Automata guardado para exportar","Automata Resultado",JOptionPane.INFORMATION_MESSAGE);
        }      
        catch(Exception err) {}
    }//GEN-LAST:event_jMenuItemExportarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        if (JOptionPane.showConfirmDialog(null,"¿Esta seguro de que desea cerrar la aplicacion?","Cerrar",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION )
            System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCargarNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarNegActionPerformed
        try {
            JPanel panel = new JPanel(); 
            Cargar_fichero c = new Cargar_fichero(panel);
            
            String tF = c.filename;
            FileReader fr = new FileReader(tF);
            BufferedReader bw = new BufferedReader(fr);
            //PrintWriter salida = new PrintWriter(bw);
            mneg.removeAllElements();
            cbMNeg.removeAllItems();
            String t = bw.readLine();
            for (int i=0; t!=null; i++) {
                mneg.addElement(t);
                cbMNeg.addItem((String)t);
                t = bw.readLine();
            }
	    bEjecutar.setEnabled(true);
        }
        catch (Exception err) {
	    JOptionPane.showMessageDialog(null,"Error al cargar muestra","Muestra negativa",JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jMenuItemCargarNegActionPerformed

    private void jMenuItemCargarPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarPosActionPerformed
        try {
            JPanel panel = new JPanel(); 
            Cargar_fichero c = new Cargar_fichero(panel);
            
            String tF = c.filename;
            FileReader fr = new FileReader(tF);
            BufferedReader bw = new BufferedReader(fr);
            //PrintWriter salida = new PrintWriter(bw);
            mpos.removeAllElements();
            cbMPos.removeAllItems();
            String t = bw.readLine();
            for (int i=0; t!=null; i++) {
                mpos.addElement(t);
                cbMPos.addItem((String)t);
                t = bw.readLine();
            }
            actualizaValoresK();
            apGenerado = false;
	    bEjecutar.setEnabled(true);
        }
        catch (Exception err) {
	    JOptionPane.showMessageDialog(null,"Error al cargar muestra","Muestra positiva",JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jMenuItemCargarPosActionPerformed

    private void jMenuItemGuardarNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarNegActionPerformed
        try {
            JPanel panel = new JPanel(); 
            Guardar_como g = new Guardar_como(panel);
            
            String tF = g.filename;
            FileWriter fw = new FileWriter(tF);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter salida = new PrintWriter(bw);
            
            for (int i=0; i<mneg.size(); i++)
                salida.println(mneg.elementAt(i));
            salida.close();
            JOptionPane.showMessageDialog(null,"Muestra guardada","Muestra Negativa",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception err) {
	    JOptionPane.showMessageDialog(null,"Error al guardar muestra","Muestra Negativa",JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jMenuItemGuardarNegActionPerformed

    private void jMenuItemGuardarPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarPosActionPerformed
        boolean inc = false;
        try {
            if (cbSelAlg.getSelectedIndex()==4) {
                if (JOptionPane.showConfirmDialog(null,"¿Desea guardar la muestra añadida?","Guardar muestra",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
                    inc = true;
            }
            JPanel panel = new JPanel(); 
            Guardar_como g = new Guardar_como(panel);
            
            String tF = g.filename;
            FileWriter fw = new FileWriter(tF);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter salida = new PrintWriter(bw);
            
            for (int i=0; i<mpos.size(); i++)
                if (!mpos.elementAt(i).equals("%")) salida.println(mpos.elementAt(i));
            if (inc) {
                for (int i=0; i<minc.size(); i++)
                    salida.println(minc.elementAt(i));
            }
            salida.close();
            JOptionPane.showMessageDialog(null,"Muestra guardada","Muestra Positiva",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception err) {
	    JOptionPane.showMessageDialog(null,"Error al guardar muestra","Muestra Positiva",JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jMenuItemGuardarPosActionPerformed
  
    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        ImageIcon icono = new ImageIcon(JFramePrincipal.class.getResource("/Interfaz/uniovi.gif"));
        
        JOptionPane.showMessageDialog(
                null,
                "Universidad de Oviedo\nE.U.I.T. Informática y Telemática de Gijón" +
                "\n\nPlataforma para la Experimentacion sobre Lenguajes Regulares\n\nAutor: Daniel Moral García\nJunio 2007",
                "PELR - Acerca de",
                JOptionPane.INFORMATION_MESSAGE
                ,icono
                );
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void bVerAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVerAPMouseClicked
        if (bVerAP.isEnabled()) {
            JFrameMostrarAP pMostrarAP = new JFrameMostrarAP(ap);
            pMostrarAP.setEnabled(true);
            pMostrarAP.setVisible(true);
        }
    }//GEN-LAST:event_bVerAPMouseClicked

    /**
     *  Funcion para ordenar un vector de string. 
     *  Necesita un vector y devuelve un vector ordenado.  
     */
    private Vector ordenaVector(Vector v) {
        String t;
        for (int i=0; i<v.size(); i++)
            for (int j=i; j<v.size(); j++) {
                if (v.elementAt(i).toString().length()>v.elementAt(j).toString().length()) {
                    t = v.elementAt(i).toString();
                    v.setElementAt(v.elementAt(j).toString(),i);
                    v.setElementAt(t,j);
                }
            }
        return v;
    }
    
    /**
     *  Funcion que genera el arbol de prefijos para la muestra dada. No necesita
     *      parametros (los coge directamente de los componentes).
     *  No devuelve nada. El resultado se almacena en la variable global que contendra
     *      al automata (en este caso "a").
    */
    private void generaAP() {
        Vector est = new Vector();
        Vector est2 = new Vector();
        Vector n = new Vector();
        Vector simb = new Vector();
        boolean esta = false;
        
        // Si el estado lambda (%) no esta ya en la muestra lo añadimos. Lambda 
        //  se añade en dos casos: al generar los valores de S y aqui, por eso es
        //  necesario comprobar que no este en el vector.
        if (!mpos.contains("%")) {
            mpos.add(0,"%");
            esta = false;
        }
        else esta = true;

        // Genera todos los estados del automata. Añade los que aparecen en la 
        //      muestra y crea todos los estados intermedios.
        for (int i=0; i<mpos.size(); i++)
        {
            if (mpos.get(i).toString().length()==1) {
                est.addElement(mpos.get(i)); 
                if (!mpos.get(i).equals("%")) simb.addElement(mpos.get(i));
            }
            else 
            {
                for (int t=1; t<=mpos.get(i).toString().length(); t++)
                {
                    String temp = mpos.get(i).toString().substring(0,t);
                    if (est.contains(temp)==false) 
                        est.addElement(temp);
                }
                for (int t=0; t<mpos.get(i).toString().length(); t++) {
                    String temp = mpos.get(i).toString().substring(t,t+1);
                    if (!simb.contains(temp)) simb.addElement(temp);
                }
            }
        }
        // Ordenacion por Burbuja del vector de estados.
        est = ordenaVector(est);
        // Añadimos el tipo de estado.
        for (int i=0; i<est.size(); i++) {
            n.add(est.elementAt(i));
            if (mpos.contains(est.elementAt(i))) {
                if (est.elementAt(i).equals("%")) {
                    if (esta) est2.addElement(new Estado(n,"INICIAL/FINAL"));
                    else est2.addElement(new Estado(n,"INICIAL"));
                }
                else est2.addElement(new Estado(n,"FINAL"));
            }
            else est2.addElement(new Estado(n,"INTERMEDIO"));
            n.removeAllElements();
        }

        ap.putVectorEstados(est2);
        ap.putAlfEntrada(mpos);
        ap.putSimbolos(simb);
        ap.limpiaTransiciones();
        
        // Con esto generamos las transiciones iniciales
        String estadoActual,s;
        int indexEstado;
        for (int i=1; i<ap.obtenerNumeroEstados(); i++) {
            estadoActual = ap.obtenerEstado(i).getEstado(0);
            s = estadoActual.substring(estadoActual.length()-1);
            if (estadoActual.length()==1) ap.addTransicion(0,simb.indexOf(s),new Estado(estadoActual));
            else {
                estadoActual = estadoActual.substring(0,estadoActual.length()-1);
                indexEstado = ap.obtenerIndiceEstado(new Estado(estadoActual));
                ap.addTransicion(indexEstado,simb.indexOf(s),ap.obtenerEstado(i));
            }
        }
        apGenerado = true;
        if (esta==false) mpos.removeElement("%");
        bVerAP.setEnabled(true);
    }
    
    private void generaS() {
        if (sCalculado == false) {
            double max = -1;
            double stren = -1;
            Vector intersec = new Vector();
            Vector aux1 = new Vector();
            Vector aux2 = new Vector();
            Vector temp = new Vector();
            String t;

            cbValoresS.removeAllItems();
            if (apGenerado == false) generaAP();

            // Esto es para saber hasta que orden hay que calcular las T's
            int longMax = ap.obtenerEstado(0).getEstado(0).length();
            for (int i=1; i<ap.obtenerNumeroEstados(); i++)
                if ( ap.obtenerEstado(i).getEstado(0).length() > longMax )
                    longMax = ap.obtenerEstado(i).getEstado(0).length();

            for (int i=0; i<ap.obtenerNumeroEstados(); i++)
                for (int j=i; j<ap.obtenerNumeroEstados(); j++) {
                    if (i!=j) {
                        max = -1;
                        for (int valk=0; valk<=longMax; valk++) {
                            aux1 = AlgoritmoIM1.Tspos(ap,ap.obtenerEstado(i),valk);
                            aux2 = AlgoritmoIM1.Tspos(ap,ap.obtenerEstado(j),valk);
                            intersec = AlgoritmoIM1.interseccion(aux1,aux2);
                            float denominador = aux1.size()+aux2.size();
                            if (denominador!=0) stren = ((2*intersec.size())/denominador);
                            else stren = 0;
                            if (stren>max) max=stren;
                        } 
                        if (!temp.contains(Double.toString(max))) { //Para saber si el valor esta repe
                            temp.addElement(Double.toString(max));
                            cbValoresS.addItem(Double.toString(max));
                            if ((max>0) && (max<miclet)) miclet=max;
                        }
                    }
                }
            sCalculado = true;
        }        
    }
    
    private void bGeneraSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGeneraSMouseClicked
        generaS();
    }//GEN-LAST:event_bGeneraSMouseClicked

    private void bDelMNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDelMNegMouseClicked
        try {
            mneg.removeElement(cbMNeg.getSelectedItem().toString());
            cbMNeg.removeItem(cbMNeg.getSelectedItem().toString());
            bEjecutar.setEnabled(true);
        }
        catch (Exception err) {}
    }//GEN-LAST:event_bDelMNegMouseClicked

    private void bDelMPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDelMPosMouseClicked
        try {
            mpos.removeElement(cbMPos.getSelectedItem().toString());
            cbMPos.removeItem(cbMPos.getSelectedItem().toString());
            bEjecutar.setEnabled(true);
            mpos = ordenaVector(mpos);
            actualizaValoresK();
            apGenerado = false;
            bVerAP.setEnabled(false);
            sCalculado = false;
        }
        catch(Exception err) {}
    }//GEN-LAST:event_bDelMPosMouseClicked

    private void bEjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEjecutarMouseClicked
        if (bEjecutar.isEnabled()) {
	    if (!mpos.isEmpty()) {
		if ((sCalculado == false) && cbSelAlg.getSelectedIndex()==1) {
		    JOptionPane.showMessageDialog(null,"Debes generar los valores de S para la nueva muestra","Faltan parámetros",JOptionPane.INFORMATION_MESSAGE);
		}
		else {
		    int x = 0;
		    a = new Automata();
		    minc.removeAllElements();
		    cbMInc.removeAllItems();
		    //Si es necesario generamos el arbol de prefijos (tambien se genera en
		    // la funcion generaS(...)
		    if (apGenerado == false) generaAP();

		    long t1 = System.currentTimeMillis();
		    switch (cbSelAlg.getSelectedIndex()) {
			case 0: // IM1 con k-sufijos
			    a = AlgoritmoIM1.ejecutar(ap,cbSelAlg.getSelectedIndex(),Integer.decode(cbValoresK.getSelectedItem().toString()).intValue(),0);
			    break;
			case 1: // IM1 con Levine
			    a = AlgoritmoIM1.ejecutar(ap,cbSelAlg.getSelectedIndex(),0,Double.valueOf(cbValoresS.getSelectedItem().toString()).doubleValue());
			    break;
			case 2: // IM1 con Miclet
			    if (sCalculado == false) generaS();
			    a = AlgoritmoIM1.ejecutar(ap,cbSelAlg.getSelectedIndex(),0,miclet);
			    break;
			case 3: // KC
			    a = AlgoritmoKC.ejecutar(ap,cbSelAlg.getSelectedIndex(),Integer.decode(cbValoresK.getSelectedItem().toString()).intValue(),mneg);
			    break;
			case 4: // KC incremental
			    a = AlgoritmoKC.ejecutar(ap,cbSelAlg.getSelectedIndex(),Integer.decode(cbValoresK.getSelectedItem().toString()).intValue(),mneg);
			    break;
			case 5: // KC con muestra negativa
			    x=0;
			    boolean reconmneg=true;
			    while ((x<cbValoresK.getItemCount())&&(reconmneg==true)) {
				a = AlgoritmoKC.ejecutar(ap,cbSelAlg.getSelectedIndex(),Integer.decode(cbValoresK.getItemAt(x).toString()).intValue(),mneg);
				reconmneg=compruebaMNeg();
				x++;
			    }
			    break;
		    }
		    long t2 = System.currentTimeMillis();

		    mostrarResultados();
		    jLabel6.setText((t2-t1)/1000+"."+(t2-t1)%1000+" segundos");
		    if (cbSelAlg.getSelectedIndex()==5) jLabelValKenKC.setText(Integer.toString(x-1));
		    if (apGenerado && cbSelAlg.getSelectedIndex()!=4) bEjecutar.setEnabled(false);
		    if (cbSelAlg.getSelectedIndex()==4) bVerAP.setEnabled(true);
		}
	    }
	    else {
		JOptionPane.showMessageDialog(null,"Debes introducir al menos una cadena para la muestra positiva","Faltan parámetros",JOptionPane.INFORMATION_MESSAGE);
	    }
	}
    }//GEN-LAST:event_bEjecutarMouseClicked

    private boolean compruebaMNeg() {
        Estado temp = new Estado();
        if (cbMNeg.getItemCount()>0) {
            for (int i=0; i<cbMNeg.getItemCount(); i++) {
                try {
                    temp = (Estado)a.getTransicionEstrella(0,cbMNeg.getItemAt(i).toString());
                    if (temp.getTipoEstado().equalsIgnoreCase("INICIAL/FINAL"))
                        return true;
                    if (temp.getTipoEstado().equalsIgnoreCase("FINAL"))
                        return true;
                }
                catch(Exception err) {
                }
            }
        }
        return false;
    }
    
    /**
     *  Funcion que muestra los resultados del algoritmo.
     *  No necesita parametros. Muestra los resultados en los componentes
     *   correspondientes.
     */
    private void mostrarResultados() {
        Estado aux = new Estado();
        Estado tmp = new Estado();
        Vector auxI = new Vector();
        Vector auxF = new Vector();
        String cad = "";
        
        //Limpiamos restos de posibles ejecuciones anteriores
        cbAlfEntrRes.removeAllItems();
        jlEstIniciales.removeAll();
        jlEstFinales.removeAll();
        
        //Rellenamos las casillas de resultado.
        Vector s = new Vector(ap.getSimbolos());
        for (int i=0; i<s.size(); i++)
            //Alfabeto de entrada (resultado)
            cbAlfEntrRes.addItem(s.elementAt(i).toString());
        for (int i=0; i<a.obtenerNumeroEstados(); i++) {
            aux = a.obtenerEstado(i);
            cad = "";
            cad = "{"+aux.getEstado(0);
            for (int k=1; k<aux.getNumEstados(); k++)
                cad = cad+","+aux.getEstado(k);
            cad = cad + "}";
            if (aux.getTipoEstado().equals("INICIAL/FINAL")) {
                auxI.addElement(cad);
                auxF.addElement(cad);
            }
            else if (aux.getTipoEstado().equals("FINAL")) {
                auxF.addElement(cad);
            }
            else if (aux.getTipoEstado().equals("INICIAL"))
                auxI.addElement(cad);
        }
        jlEstIniciales.setListData(auxI);
        jlEstFinales.setListData(auxF);
        
        // Ahora mostramos las transiciones y los estados
        ModeloTabla miModelo = new ModeloTabla(a.obtenerNumeroEstados(),s.size()+1);
        miModelo.setNombreColumna(0,"Estados");
        for (int i=0; i<s.size(); i++)
             miModelo.setNombreColumna(i+1,s.elementAt(i).toString());
        Vector vtmp = new Vector();
        cad = "";
        int k;
        for (int i=0; i<a.obtenerNumeroEstados(); i++) {
            tmp = a.obtenerEstado(i);
            cad = "{"+(String)tmp.getNombreEstado().elementAt(0);
            for (int j=1; j<tmp.obtenerNumeroEstados(); j++) {
                cad = cad+",";
                cad = cad+(String)tmp.getNombreEstado().elementAt(j);
            }
            cad = cad + "}";
            miModelo.setValueAt(cad,i,0);
            for (int j=0; j<s.size(); j++) {
                try {
                    vtmp = (Vector)a.getTransicion(i,j);
                    for (int z=0; z<vtmp.size(); z++) {
                        cad = "";
                        tmp = (Estado)vtmp.elementAt(z);
                        cad = "{"+tmp.getEstado(0);
                        for (k=1; k<tmp.getNumEstados(); k++)
                            cad = cad+","+tmp.getEstado(k);
                        cad = cad + "}";
                    }
                    miModelo.setValueAt(cad,i,j+1);
                }
                catch (Exception error) {
                    miModelo.setValueAt("-",i,j+1);
                }
            }
        }
        tFunDelta.setModel(miModelo);
    }
    
    private void bAddMNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddMNegMouseClicked
        try {
            if (tbMNeg.getText().length() > 0) {
                if (mpos.contains(tbMNeg.getText())) {
                    JOptionPane.showMessageDialog(null,"Esa cadena pertenece a la muestra positiva","Muestra Negativa",JOptionPane.ERROR_MESSAGE);
                }
                else {
                    if (!mneg.contains(tbMNeg.getText())) {
                        mneg.add(tbMNeg.getText());
                        cbMNeg.addItem((String)tbMNeg.getText());
                        bEjecutar.setEnabled(true);
                    }
                }
            }
        }
        catch (NullPointerException err) {}
        tbMNeg.setText("");
        tbMNeg.requestFocus();
        //Reordenamos el vector
        for (int i=0; i<mneg.size(); i++)
            for (int j=i; j<mneg.size(); j++) {
                if (mneg.elementAt(i).toString().length()>mneg.elementAt(j).toString().length()) {
                    String t = mneg.elementAt(i).toString();
                    mneg.setElementAt(mneg.elementAt(j).toString(),i);
                    mneg.setElementAt(t,j);
                }
            }
    }//GEN-LAST:event_bAddMNegMouseClicked
  
    private void bAddMPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddMPosMouseClicked
        try {
            if (tbMPos.getText().length() > 0) {
                if (mneg.contains(tbMPos.getText())) {
                    JOptionPane.showMessageDialog(null,"Esa cadena pertenece a la muestra negativa","Muestra Positiva",JOptionPane.ERROR_MESSAGE);
                }
                else {
                    if (!mpos.contains(tbMPos.getText())) {
                        mpos.add(tbMPos.getText());
                        cbMPos.addItem((String)tbMPos.getText());
                        bEjecutar.setEnabled(true);
                        apGenerado = false;
                        bVerAP.setEnabled(false);
                        sCalculado = false;
                    }
                }
            }
        }
        catch (NullPointerException err) {}
        tbMPos.setText("");
        tbMPos.requestFocus();
        //Reordenamos el vector
        mpos = ordenaVector(mpos);
        //Actualizamos cbValoresK
        actualizaValoresK();
    }//GEN-LAST:event_bAddMPosMouseClicked

    private void actualizaValoresK() {
        cbValoresK.removeAllItems();
        String s = (String)mpos.elementAt(mpos.size()-1);
        for (int i=0; i<=s.length(); i++)
            cbValoresK.addItem(Integer.toString(i));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCadenaKC;
    private javax.swing.JButton bAddMNeg;
    private javax.swing.JButton bAddMPos;
    private javax.swing.JButton bBorrarMNeg;
    private javax.swing.JButton bBorrarMPos;
    private javax.swing.JButton bDelMNeg;
    private javax.swing.JButton bDelMPos;
    private javax.swing.JButton bEjecutar;
    private javax.swing.JButton bGeneraS;
    private javax.swing.JButton bVerAP;
    private javax.swing.JComboBox cbAlfEntrRes;
    private javax.swing.JComboBox cbMInc;
    private javax.swing.JComboBox cbMNeg;
    private javax.swing.JComboBox cbMPos;
    private javax.swing.JComboBox cbSelAlg;
    private javax.swing.JComboBox cbValoresK;
    private javax.swing.JComboBox cbValoresS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelKCNeg;
    private javax.swing.JLabel jLabelValKenKC;
    private javax.swing.JMenu jMenuApGuardar;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAutomata;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGuardar;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemApCompacto;
    private javax.swing.JMenuItem jMenuItemApNormal;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemCargarNeg;
    private javax.swing.JMenuItem jMenuItemCargarPos;
    private javax.swing.JMenuItem jMenuItemCompacto;
    private javax.swing.JMenuItem jMenuItemExportar;
    private javax.swing.JMenuItem jMenuItemGuardarNeg;
    private javax.swing.JMenuItem jMenuItemGuardarPos;
    private javax.swing.JMenuItem jMenuItemNormal;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemValidar;
    private javax.swing.JMenuItem jMenuItemValidarConjunto;
    private javax.swing.JMenu jMenuMuestraNeg;
    private javax.swing.JMenu jMenuMuestraPos;
    private javax.swing.JMenu jMenuValidar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneFD;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList jlEstFinales;
    private javax.swing.JList jlEstIniciales;
    private javax.swing.JLabel lAlfEntrRes;
    private javax.swing.JLabel lDeltaRes;
    private javax.swing.JLabel lEstFinales;
    private javax.swing.JLabel lEstIniciales;
    private javax.swing.JLabel lSelAlg;
    private javax.swing.JPanel pParametros;
    private javax.swing.JPanel pResultados;
    private javax.swing.JTable tFunDelta;
    private javax.swing.JTextField tbAddCadenaKC;
    private javax.swing.JTextField tbMNeg;
    private javax.swing.JTextField tbMPos;
    // End of variables declaration//GEN-END:variables
    
}
