/*
 * JFramePrincipal.java
 *
 * Created on 11 de mayo de 2007, 14:49
 */

package lanzadorpelr;

import javax.swing.JOptionPane;

/**
 *
 * @author  Daniel Moral García
 */
public class JFramePrincipal extends javax.swing.JFrame {
    
    /** Creates new form JFramePrincipal */
    public JFramePrincipal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new javax.swing.JToolBar();
        bModulo1 = new javax.swing.JButton();
        bModulo2 = new javax.swing.JButton();
        bModulo3 = new javax.swing.JButton();
        bModulo4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanzador PELR");
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getAccessibleContext().setAccessibleParent(this);
        jToolBar1.setFloatable(false);
        bModulo1.setText("Aut\u00f3matas");
        bModulo1.setToolTipText("Operaciones con aut\u00f3matas");
        bModulo1.setEnabled(false);
        bModulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModulo1MouseClicked(evt);
            }
        });

        jToolBar1.add(bModulo1);

        bModulo2.setText("Inducci\u00f3n");
        bModulo2.setToolTipText("Algoritmos de inducci\u00f3n de aut\u00f3matas");
        bModulo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModulo2MouseClicked(evt);
            }
        });

        jToolBar1.add(bModulo2);

        bModulo3.setText("Gram\u00e1ticas");
        bModulo3.setEnabled(false);
        bModulo3.setFocusable(false);
        jToolBar1.add(bModulo3);

        bModulo4.setText("Moore/Mealy");
        bModulo4.setEnabled(false);
        bModulo4.setFocusable(false);
        jToolBar1.add(bModulo4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModulo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModulo1MouseClicked
        /*Runtime rt = Runtime.getRuntime();
        try {
            rt.exec("PELR1/pelr.exe");
        }
        catch(Exception err) {
            JOptionPane.showMessageDialog(null,"No se ha podido cargar la aplicacion\nAsegurate de que este bien instalada","Error de carga",JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_bModulo1MouseClicked

    private void bModulo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModulo2MouseClicked
        Runtime rt = Runtime.getRuntime();
        try {
            rt.exec("java.exe -jar PELR2/PELR.jar");
        }
        catch(Exception err) {
            JOptionPane.showMessageDialog(null,"No se ha podido cargar la aplicacion\nAsegurate de que este bien instalada","Error de carga",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bModulo2MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModulo1;
    private javax.swing.JButton bModulo2;
    private javax.swing.JButton bModulo3;
    private javax.swing.JButton bModulo4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
